# Generated by Django 5.2.13 on 2026-05-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_remove_item_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Código interno / SKU. Déjelo en blanco para generar automáticamente.",
                max_length=20,
                verbose_name="código",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="unit",
            field=models.CharField(
                choices=[
                    ("UNIT", "Unidad"),
                    ("LB", "Libra"),
                    ("HOUR", "Hora"),
                    ("KG", "Kilogramo"),
                    ("BOX", "Caja"),
                    ("SERVICE", "Servicio"),
                    ("METER", "Metro"),
                    ("LITER", "Litro"),
                    ("OTHER", "Otro"),
                ],
                default="UNIT",
                max_length=10,
                verbose_name="unidad de medida",
            ),
        ),
    ]
