# Generated by Django 5.2.13 on 2026-05-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_simple_history_invoice_customer_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="precio de costo",
            ),
        ),
    ]
