# Generated by Django 5.2.13 on 2026-05-16 12:16

import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_organization_logo_alter_user_avatar_and_more"),
        ("items", "0006_search_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalItem",
            fields=[
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Código interno / SKU. Déjelo en blanco para generar automáticamente.",
                        max_length=20,
                        verbose_name="código",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nombre")),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("SALE", "Venta"),
                            ("PURCHASE", "Compra"),
                            ("BOTH", "Venta y Compra"),
                        ],
                        db_index=True,
                        default="BOTH",
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("UNIT", "Unidad"),
                            ("LB", "Libra"),
                            ("HOUR", "Hora"),
                            ("KG", "Kilogramo"),
                            ("BOX", "Caja"),
                            ("SERVICE", "Servicio"),
                            ("METER", "Metro"),
                            ("LITER", "Litro"),
                            ("OTHER", "Otro"),
                        ],
                        default="UNIT",
                        max_length=10,
                        verbose_name="unidad de medida",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="precio de venta",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="precio de costo",
                    ),
                ),
                (
                    "itbis_rate",
                    models.CharField(
                        choices=[
                            ("EXEMPT", "Exento (0%)"),
                            ("RATE_0", "Tasa 0% (exportación)"),
                            ("RATE_16", "ITBIS 16%"),
                            ("RATE_18", "ITBIS 18%"),
                        ],
                        default="RATE_18",
                        max_length=8,
                        verbose_name="tasa ITBIS",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("notes", models.TextField(blank=True, verbose_name="notas internas")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.organization",
                        verbose_name="organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical artículo",
                "verbose_name_plural": "historical artículos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
