# Generated by Django 5.2.13 on 2026-05-23 23:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0007_historicalitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalitem",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="precio de costo",
            ),
        ),
        migrations.AlterField(
            model_name="historicalitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="precio de venta",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="precio de costo",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="precio de venta",
            ),
        ),
    ]
