# Generated by Django 5.2.14 on 2026-05-28 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0008_add_price_min_validators"),
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalitem",
            name="default_supplier",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="purchases.supplier",
                verbose_name="proveedor habitual",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="default_supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_items",
                to="purchases.supplier",
                verbose_name="proveedor habitual",
            ),
        ),
    ]
