# Generated by Django 5.2.13 on 2026-06-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_securityauditevent"),
        ("items", "0011_simplify_itbis_remove_rate0"),
        ("purchases", "0007_alter_historicalsupplier_id_type_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["organization", "is_active"], name="item_org_active_idx"
            ),
        ),
    ]
