# Generated by Django 5.2.13 on 2026-05-01 02:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="contact_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="nombre de contacto"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="contact_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="número de contacto"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="rnc_cedula",
            field=models.CharField(
                blank=True,
                help_text="RNC: 9 dígitos. Cédula: 11 dígitos. Opcional en Factura de Consumo < RD$250,000.",
                max_length=20,
                verbose_name="RNC / Cédula",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="encf",
            field=models.CharField(
                blank=True,
                help_text="Número de Comprobante Fiscal Electrónico asignado por la DGII. Se genera automáticamente al confirmar la factura.",
                max_length=13,
                verbose_name="e-NCF",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="encf_modified",
            field=models.ForeignKey(
                blank=True,
                help_text="Obligatorio para Notas de Crédito (34) y Débito (33).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_debit_notes",
                to="invoices.invoice",
                verbose_name="NCF afectado",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("1.0000"),
                help_text="Tasa BCR si la moneda no es DOP.",
                max_digits=12,
                verbose_name="tasa de cambio",
            ),
        ),
        migrations.AlterField(
            model_name="ncfsequence",
            name="series",
            field=models.CharField(
                default="E",
                help_text="'E' para electrónico (e-CF). 'B' para comprobantes físicos legacy.",
                max_length=1,
                verbose_name="serie",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="Número de cheque, confirmación de transferencia, etc.",
                max_length=100,
                verbose_name="referencia",
            ),
        ),
    ]
