# Generated by Django 5.2.13 on 2026-05-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_add_contact_fields_to_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="rnc_cedula",
            field=models.CharField(
                help_text="RNC: 9 dígitos. Cédula: 11 dígitos. Opcional en Factura de Consumo < RD$250,000.",
                max_length=20,
                verbose_name="RNC / Cédula",
            ),
        ),
    ]
