# Generated by Django 5.2.13 on 2026-05-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_customer_rnc_cedula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="rnc_cedula",
            field=models.CharField(
                help_text="RNC: 9 dígitos. Cédula: 11 dígitos.",
                max_length=20,
                verbose_name="RNC / Cédula",
            ),
        ),
    ]
