# Generated by Django 5.2.13 on 2026-05-01 22:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_alter_customer_rnc_cedula"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="descripción"
                    ),
                ),
                (
                    "days_due",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número de días para este término de pago.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(365),
                        ],
                        verbose_name="días de vencimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "término de pago",
                "verbose_name_plural": "términos de pago",
                "ordering": ["days_due", "name"],
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="payment_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="invoices.paymentterm",
                verbose_name="término de pago",
            ),
        ),
    ]
