# Generated by Django 5.2.13 on 2026-05-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_add_default_payment_method_to_customer"),
        ("sales", "0010_customer_department"),
    ]

    operations = []
