# Generated by Django 5.2.13 on 2026-05-04 22:21

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_invitation_options_alter_membership_options_and_more"),
        ("sales", "0014_paymentterm_organization_invoice_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "documento",
                "verbose_name_plural": "documentos",
            },
        ),
        migrations.AlterModelOptions(
            name="invoiceitem",
            options={
                "ordering": ["pk"],
                "verbose_name": "línea de documento",
                "verbose_name_plural": "líneas de documento",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "pago",
                "verbose_name_plural": "pagos",
            },
        ),
        migrations.AlterField(
            model_name="customerdepartment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="customerdepartment",
            name="name",
            field=models.CharField(
                help_text="Ej.: Almacén Central, Depósito, Oficina Gerencial",
                max_length=200,
                verbose_name="nombre del departamento",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Departamento o sucursal del cliente al que se entrega esta orden.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_orders",
                to="invoices.customerdepartment",
                verbose_name="departamento de entrega",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Borrador"),
                    ("CONFIRMED", "Confirmada"),
                    ("CANCELLED", "Anulada"),
                    ("SENT", "Enviada"),
                    ("PAID", "Pagada"),
                    ("OVERDUE", "Vencida"),
                    ("ACCEPTED", "Aceptada"),
                    ("REJECTED", "Rechazada"),
                    ("EXPIRED", "Expirada"),
                    ("CONVERTED", "Convertida"),
                    ("DELIVERED", "Entregada"),
                    ("INVOICED", "Facturada"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=12,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="valid_until",
            field=models.DateField(
                blank=True,
                help_text="Fecha de vencimiento de la cotización.",
                null=True,
                verbose_name="válida hasta",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="invoices.invoice",
                verbose_name="documento",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=14, verbose_name="monto total recibido"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("CASH", "Efectivo"),
                    ("CHECK", "Cheque"),
                    ("TRANSFER", "Transferencia bancaria"),
                ],
                default="TRANSFER",
                max_length=10,
                verbose_name="forma de pago",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="Número de cheque o confirmación de transferencia bancaria.",
                max_length=100,
                verbose_name="referencia",
            ),
        ),
        migrations.AlterField(
            model_name="paymentterm",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Dejar en blanco para términos globales compartidos entre organizaciones.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_terms",
                to="accounts.organization",
                verbose_name="organización",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalCustomer",
            fields=[
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="nombre / razón social"
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("RNC", "RNC"),
                            ("CED", "Cédula"),
                            ("PAS", "Pasaporte"),
                            ("EXT", "Identificación extranjera"),
                        ],
                        default="RNC",
                        max_length=3,
                        verbose_name="tipo de identificación",
                    ),
                ),
                (
                    "rnc_cedula",
                    models.CharField(
                        help_text="RNC: 9 dígitos. Cédula: 11 dígitos.",
                        max_length=20,
                        verbose_name="RNC / Cédula",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo electrónico"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="teléfono"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="nombre de contacto"
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="número de contacto"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="dirección"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="ciudad"),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="provincia"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="República Dominicana",
                        max_length=100,
                        verbose_name="país",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monto máximo de crédito autorizado. Dejar en blanco para sin límite.",
                        max_digits=14,
                        null=True,
                        verbose_name="límite de crédito",
                    ),
                ),
                (
                    "default_ncf_type",
                    models.IntegerField(
                        choices=[
                            (31, "31 – Factura de Crédito Fiscal"),
                            (32, "32 – Factura de Consumo"),
                            (33, "33 – Nota de Débito"),
                            (34, "34 – Nota de Crédito"),
                            (41, "41 – Comprobante de Compras"),
                            (43, "43 – Gastos Menores"),
                            (44, "44 – Regímenes Especiales"),
                            (45, "45 – Gubernamental"),
                            (46, "46 – Exportaciones"),
                            (47, "47 – Pagos al Exterior"),
                        ],
                        default=31,
                        verbose_name="tipo de comprobante por defecto",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.organization",
                        verbose_name="organización",
                    ),
                ),
                (
                    "payment_term",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="invoices.paymentterm",
                        verbose_name="término de pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical cliente",
                "verbose_name_plural": "historical clientes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInvoice",
            fields=[
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("INVOICE", "Factura"),
                            ("QUOTATION", "Cotización"),
                            ("SALE_ORDER", "Orden de Venta"),
                        ],
                        db_index=True,
                        default="INVOICE",
                        max_length=20,
                        verbose_name="tipo de documento",
                    ),
                ),
                (
                    "encf",
                    models.CharField(
                        blank=True,
                        help_text="Número de Comprobante Fiscal Electrónico asignado por la DGII. Se genera automáticamente al confirmar la factura.",
                        max_length=13,
                        verbose_name="e-NCF",
                    ),
                ),
                (
                    "ncf_type",
                    models.IntegerField(
                        choices=[
                            (31, "31 – Factura de Crédito Fiscal"),
                            (32, "32 – Factura de Consumo"),
                            (33, "33 – Nota de Débito"),
                            (34, "34 – Nota de Crédito"),
                            (41, "41 – Comprobante de Compras"),
                            (43, "43 – Gastos Menores"),
                            (44, "44 – Regímenes Especiales"),
                            (45, "45 – Gubernamental"),
                            (46, "46 – Exportaciones"),
                            (47, "47 – Pagos al Exterior"),
                        ],
                        default=31,
                        verbose_name="tipo de comprobante",
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Asignado automáticamente al confirmar (COT-YYYY-NNNN / OV-YYYY-NNNN).",
                        max_length=20,
                        verbose_name="número de documento",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="fecha de emisión",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de vencimiento"
                    ),
                ),
                (
                    "payment_condition",
                    models.CharField(
                        choices=[
                            ("CASH", "Contado"),
                            ("CREDIT", "Crédito"),
                            ("FREE", "Gratuito"),
                            ("OTHER", "Otro"),
                        ],
                        default="CASH",
                        max_length=10,
                        verbose_name="condición de pago",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de vencimiento de la cotización.",
                        null=True,
                        verbose_name="válida hasta",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de entrega"
                    ),
                ),
                (
                    "signed_by",
                    models.CharField(
                        blank=True,
                        help_text="Nombre de la persona que recibió y firmó la entrega.",
                        max_length=150,
                        verbose_name="recibido por",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("DOP", "Peso Dominicano (DOP)"),
                            ("USD", "Dólar Americano (USD)"),
                            ("EUR", "Euro (EUR)"),
                        ],
                        default="DOP",
                        max_length=3,
                        verbose_name="moneda",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        help_text="Tasa BCR si la moneda no es DOP.",
                        max_digits=12,
                        verbose_name="tasa de cambio",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="subtotal (sin ITBIS)",
                    ),
                ),
                (
                    "itbis_18",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="ITBIS 18%",
                    ),
                ),
                (
                    "itbis_16",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="ITBIS 16%",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="total",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("CONFIRMED", "Confirmada"),
                            ("CANCELLED", "Anulada"),
                            ("SENT", "Enviada"),
                            ("PAID", "Pagada"),
                            ("OVERDUE", "Vencida"),
                            ("ACCEPTED", "Aceptada"),
                            ("REJECTED", "Rechazada"),
                            ("EXPIRED", "Expirada"),
                            ("CONVERTED", "Convertida"),
                            ("DELIVERED", "Entregada"),
                            ("INVOICED", "Facturada"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas internas")),
                (
                    "terms",
                    models.TextField(blank=True, verbose_name="términos y condiciones"),
                ),
                ("xml_content", models.TextField(blank=True, verbose_name="XML e-CF")),
                (
                    "dgii_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("ACCEPTED", "Aceptada"),
                            ("REJECTED", "Rechazada"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="estado DGII",
                    ),
                ),
                (
                    "dgii_track_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="track ID DGII"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "consolidated_into",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Factura que consolidó esta orden de venta.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="invoices.invoice",
                        verbose_name="consolidada en",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="invoices.customer",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Departamento o sucursal del cliente al que se entrega esta orden.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="invoices.customerdepartment",
                        verbose_name="departamento de entrega",
                    ),
                ),
                (
                    "encf_modified",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Obligatorio para Notas de Crédito (34) y Débito (33).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="invoices.invoice",
                        verbose_name="NCF afectado",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.organization",
                        verbose_name="organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical documento",
                "verbose_name_plural": "historical documentos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPayment",
            fields=[
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="monto total recibido",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="fecha de pago"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Efectivo"),
                            ("CHECK", "Cheque"),
                            ("TRANSFER", "Transferencia bancaria"),
                        ],
                        default="TRANSFER",
                        max_length=10,
                        verbose_name="forma de pago",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Número de cheque o confirmación de transferencia bancaria.",
                        max_length=100,
                        verbose_name="referencia",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="invoices.customer",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.organization",
                        verbose_name="organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pago",
                "verbose_name_plural": "historical pagos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
