# Generated by Django 5.2.13 on 2026-05-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0016_ncf_traditional_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ncfsequence",
            name="series",
            field=models.CharField(
                choices=[
                    ("B", "B – Físico (comprobante tradicional)"),
                    ("E", "E – Electrónico (e-CF)"),
                ],
                default="B",
                max_length=1,
                verbose_name="serie",
            ),
        ),
    ]
