# Generated by Django 5.2.14 on 2026-05-24 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0008_add_price_min_validators"),
        ("sales", "0023_rename_db_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesdocumentitem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="line_items",
                to="items.item",
                verbose_name="artículo",
            ),
        ),
    ]
