# Generated by Django 5.2.14 on 2026-05-24

import decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0024_integrity_authorization_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.01"))],
                verbose_name="monto total recibido",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.01"))],
                verbose_name="monto total recibido",
            ),
        ),
        migrations.AlterField(
            model_name="paymentallocation",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.01"))],
                verbose_name="monto aplicado",
            ),
        ),
        migrations.AlterField(
            model_name="salesdocumentitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=4,
                default=decimal.Decimal("1.0000"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.0001"))],
                verbose_name="cantidad",
            ),
        ),
        migrations.AlterField(
            model_name="salesdocumentitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.00"))],
                verbose_name="precio unitario (sin ITBIS)",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="payment_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="allocation_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesdocumentitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="sales_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesdocumentitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="sales_line_unit_price_nonnegative",
            ),
        ),
    ]
