# Generated by Django 5.2.13 on 2026-06-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0026_data_itbis_rate0_to_exempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesdocumentitem",
            name="itbis_rate",
            field=models.CharField(
                choices=[("EXEMPT", "0%"), ("RATE_16", "16%"), ("RATE_18", "18%")],
                default="RATE_18",
                max_length=8,
                verbose_name="tasa ITBIS",
            ),
        ),
    ]
