# Generated by Django 5.2.13 on 2026-06-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_securityauditevent"),
        ("items", "0012_item_item_org_active_idx"),
        ("sales", "0028_alter_customer_id_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpayment",
            name="method",
            field=models.CharField(
                choices=[
                    ("CASH", "Efectivo"),
                    ("CHECK", "Cheque"),
                    ("TRANSFER", "Transf. bancaria"),
                ],
                default="TRANSFER",
                max_length=10,
                verbose_name="forma de pago",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpayment",
            name="reference",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="referencia"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("CASH", "Efectivo"),
                    ("CHECK", "Cheque"),
                    ("TRANSFER", "Transf. bancaria"),
                ],
                default="TRANSFER",
                max_length=10,
                verbose_name="forma de pago",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reference",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="referencia"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["organization", "date"], name="payment_org_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["organization", "customer", "date"],
                name="payment_org_cust_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salesdocument",
            index=models.Index(
                fields=["organization", "doc_type", "status", "issue_date"],
                name="inv_org_dt_status_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salesdocument",
            index=models.Index(
                fields=["organization", "doc_type", "issue_date"],
                name="inv_org_dt_issuedate_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salesdocumentitem",
            index=models.Index(
                fields=["document", "itbis_rate"], name="sales_item_doc_itbis_idx"
            ),
        ),
    ]
