# Generated by Django 6.0.6 on 2026-06-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0033_remove_documentsequence"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salesdocumentitem",
            options={
                "ordering": ["sort_order", "pk"],
                "verbose_name": "línea de documento",
                "verbose_name_plural": "líneas de documento",
            },
        ),
        migrations.AddField(
            model_name="salesdocumentitem",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
