# Generated by Django 5.2.13 on 2026-04-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_invitation"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="modules",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to grant access to all modules.",
                related_name="teams",
                to="core.module",
                verbose_name="Module access",
            ),
        ),
    ]
