# Generated by Django 5.2.13 on 2026-05-08 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_invitation_options_alter_membership_options_and_more"),
        ("core", "0002_notification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invitation",
            options={
                "verbose_name": "invitación",
                "verbose_name_plural": "invitaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="membership",
            options={"verbose_name": "membresía", "verbose_name_plural": "membresías"},
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "verbose_name": "organización",
                "verbose_name_plural": "organizaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "equipo", "verbose_name_plural": "equipos"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "usuario", "verbose_name_plural": "usuarios"},
        ),
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Propietario"),
                    ("admin", "Administrador"),
                    ("member", "Miembro"),
                    ("viewer", "Observador"),
                ],
                default="member",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Propietario"),
                    ("admin", "Administrador"),
                    ("member", "Miembro"),
                    ("viewer", "Observador"),
                ],
                default="member",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="dirección"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="ciudad"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="country",
            field=models.CharField(blank=True, max_length=100, verbose_name="país"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="correo electrónico"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="activo"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="org_logos/", verbose_name="logotipo"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=255, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_organizations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="propietario",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="teléfono"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="state",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="provincia"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="tax_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="RNC/Cédula"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="website",
            field=models.URLField(blank=True, verbose_name="sitio web"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="zip_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="código postal"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="modules",
            field=models.ManyToManyField(
                blank=True,
                help_text="Dejar vacío para conceder acceso a todos los módulos.",
                related_name="teams",
                to="core.module",
                verbose_name="acceso a módulos",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                verbose_name="foto de perfil",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="correo electrónico"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="activo"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="estado de staff"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="apellido"),
        ),
    ]
