# Generated by Django 5.2.13 on 2026-05-20 23:13

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_organization_logo_alter_user_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="signature",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[apps.accounts.validators.validate_image_size],
                verbose_name="firma",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="signatures/",
                validators=[apps.accounts.validators.validate_image_size],
                verbose_name="firma",
            ),
        ),
    ]
