# Generated by Django 5.2.14 on 2026-05-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_signature"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invitation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "invitación",
                "verbose_name_plural": "invitaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="membership",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "membresía",
                "verbose_name_plural": "membresías",
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "organización",
                "verbose_name_plural": "organizaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="team",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "equipo",
                "verbose_name_plural": "equipos",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "usuario",
                "verbose_name_plural": "usuarios",
            },
        ),
        migrations.AddField(
            model_name="historicalorganization",
            name="is_auto_created_workspace",
            field=models.BooleanField(
                default=False, verbose_name="espacio creado automáticamente"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_auto_created_workspace",
            field=models.BooleanField(
                default=False, verbose_name="espacio creado automáticamente"
            ),
        ),
    ]
