# Generated by Django 5.2.14 on 2026-05-25 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_integrity_authorization_updates"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Inicio de sesión exitoso"),
                            ("login_failed", "Inicio de sesión fallido"),
                            ("logout", "Cierre de sesión"),
                            ("session_idle_expired", "Sesión expirada por inactividad"),
                            (
                                "session_absolute_expired",
                                "Sesión expirada por límite máximo",
                            ),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=200)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_audit_events",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "evento de seguridad",
                "verbose_name_plural": "eventos de seguridad",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_se_user_id_c5577a_idx",
                    ),
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="accounts_se_organiz_c984e0_idx",
                    ),
                ],
            },
        ),
    ]
