# Generated by Django 5.2.13 on 2026-05-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_alter_customer_rnc_cedula"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="default_payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Efectivo"),
                    ("CHECK", "Cheque"),
                    ("CARD", "Tarjeta de crédito/débito"),
                    ("TRANSFER", "Transferencia bancaria"),
                    ("SWAP", "Permuta"),
                    ("OTHER", "Otro"),
                ],
                default="TRANSFER",
                max_length=10,
                verbose_name="forma de pago por defecto",
            ),
        ),
    ]
