# Generated by Django 5.2.14 on 2026-05-28 22:27

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0010_securityauditevent"),
        ("items", "0008_add_price_min_validators"),
        ("sales", "0025_financial_integrity_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSupplier",
            fields=[
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="nombre / razón social"
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("RNC", "RNC"),
                            ("CED", "Cédula"),
                            ("PAS", "Pasaporte"),
                            ("EXT", "Identificación extranjera"),
                        ],
                        default="RNC",
                        max_length=3,
                        verbose_name="tipo de identificación",
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        help_text="RNC: 9 dígitos. Cédula: 11 dígitos.",
                        max_length=20,
                        verbose_name="RNC / Cédula",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo electrónico"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="teléfono"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="nombre de contacto"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="dirección"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="ciudad"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="límite de crédito",
                    ),
                ),
                (
                    "default_ncf_type",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de NCF que emite el proveedor (ej. B01, B11).",
                        max_length=10,
                        verbose_name="tipo NCF proveedor",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.organization",
                        verbose_name="organización",
                    ),
                ),
                (
                    "payment_term",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sales.paymentterm",
                        verbose_name="término de pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical proveedor",
                "verbose_name_plural": "historical proveedores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="PurchaseSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        default="OC", max_length=5, verbose_name="prefijo"
                    ),
                ),
                (
                    "next_value",
                    models.PositiveIntegerField(
                        default=1, verbose_name="próximo valor"
                    ),
                ),
                (
                    "padding",
                    models.PositiveSmallIntegerField(default=5, verbose_name="dígitos"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_sequence",
                        to="accounts.organization",
                        verbose_name="organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "secuencia de órdenes de compra",
                "verbose_name_plural": "secuencias de órdenes de compra",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="nombre / razón social"
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("RNC", "RNC"),
                            ("CED", "Cédula"),
                            ("PAS", "Pasaporte"),
                            ("EXT", "Identificación extranjera"),
                        ],
                        default="RNC",
                        max_length=3,
                        verbose_name="tipo de identificación",
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        help_text="RNC: 9 dígitos. Cédula: 11 dígitos.",
                        max_length=20,
                        verbose_name="RNC / Cédula",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo electrónico"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="teléfono"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="nombre de contacto"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="dirección"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="ciudad"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="límite de crédito",
                    ),
                ),
                (
                    "default_ncf_type",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de NCF que emite el proveedor (ej. B01, B11).",
                        max_length=10,
                        verbose_name="tipo NCF proveedor",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="accounts.organization",
                        verbose_name="organización",
                    ),
                ),
                (
                    "payment_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suppliers",
                        to="sales.paymentterm",
                        verbose_name="término de pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "proveedor",
                "verbose_name_plural": "proveedores",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE_ORDER", "Orden de Compra"),
                            ("SUPPLIER_INVOICE", "Factura de Proveedor"),
                        ],
                        db_index=True,
                        default="PURCHASE_ORDER",
                        max_length=20,
                        verbose_name="tipo de documento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("CONFIRMED", "Confirmada"),
                            ("RECEIVED", "Recibida"),
                            ("CANCELLED", "Anulada"),
                            ("PAID", "Pagada"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=30,
                        verbose_name="número de documento",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="fecha de emisión",
                    ),
                ),
                (
                    "expected_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha estimada de entrega"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de vencimiento"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("DOP", "Peso Dominicano (DOP)"),
                            ("USD", "Dólar Americano (USD)"),
                            ("EUR", "Euro (EUR)"),
                        ],
                        default="DOP",
                        max_length=3,
                        verbose_name="moneda",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        max_digits=12,
                        verbose_name="tasa de cambio",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="subtotal (sin ITBIS)",
                    ),
                ),
                (
                    "itbis_18",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="ITBIS 18%",
                    ),
                ),
                (
                    "itbis_16",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="ITBIS 16%",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="total",
                    ),
                ),
                (
                    "supplier_ncf",
                    models.CharField(
                        blank=True, max_length=13, verbose_name="NCF del proveedor"
                    ),
                ),
                (
                    "supplier_ncf_type",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="tipo NCF del proveedor"
                    ),
                ),
                (
                    "supplier_rnc",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="RNC del proveedor"
                    ),
                ),
                (
                    "linked_purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_invoices_from_po",
                        to="purchases.purchasedocument",
                        verbose_name="orden de compra origen",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_documents",
                        to="accounts.organization",
                        verbose_name="organización",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_documents",
                        to="purchases.supplier",
                        verbose_name="proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento de compra",
                "verbose_name_plural": "documentos de compra",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalSupplierPayment",
            fields=[
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="monto total pagado",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="fecha de pago"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Efectivo"),
                            ("CHECK", "Cheque"),
                            ("TRANSFER", "Transferencia bancaria"),
                        ],
                        default="TRANSFER",
                        max_length=10,
                        verbose_name="forma de pago",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="referencia"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.organization",
                        verbose_name="organización",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="purchases.supplier",
                        verbose_name="proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pago a proveedor",
                "verbose_name_plural": "historical pagos a proveedores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSupplierDepartment",
            fields=[
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="nombre del departamento"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.organization",
                        verbose_name="organización",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="purchases.supplier",
                        verbose_name="proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical departamento de proveedor",
                "verbose_name_plural": "historical departamentos de proveedor",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPurchaseDocument",
            fields=[
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE_ORDER", "Orden de Compra"),
                            ("SUPPLIER_INVOICE", "Factura de Proveedor"),
                        ],
                        db_index=True,
                        default="PURCHASE_ORDER",
                        max_length=20,
                        verbose_name="tipo de documento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("CONFIRMED", "Confirmada"),
                            ("RECEIVED", "Recibida"),
                            ("CANCELLED", "Anulada"),
                            ("PAID", "Pagada"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=30,
                        verbose_name="número de documento",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="fecha de emisión",
                    ),
                ),
                (
                    "expected_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha estimada de entrega"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de vencimiento"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("DOP", "Peso Dominicano (DOP)"),
                            ("USD", "Dólar Americano (USD)"),
                            ("EUR", "Euro (EUR)"),
                        ],
                        default="DOP",
                        max_length=3,
                        verbose_name="moneda",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        max_digits=12,
                        verbose_name="tasa de cambio",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="subtotal (sin ITBIS)",
                    ),
                ),
                (
                    "itbis_18",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="ITBIS 18%",
                    ),
                ),
                (
                    "itbis_16",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="ITBIS 16%",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="total",
                    ),
                ),
                (
                    "supplier_ncf",
                    models.CharField(
                        blank=True, max_length=13, verbose_name="NCF del proveedor"
                    ),
                ),
                (
                    "supplier_ncf_type",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="tipo NCF del proveedor"
                    ),
                ),
                (
                    "supplier_rnc",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="RNC del proveedor"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.organization",
                        verbose_name="organización",
                    ),
                ),
                (
                    "linked_purchase_order",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="purchases.purchasedocument",
                        verbose_name="orden de compra origen",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="purchases.supplier",
                        verbose_name="proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical documento de compra",
                "verbose_name_plural": "historical documentos de compra",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SupplierDepartment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="nombre del departamento"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_departments",
                        to="accounts.organization",
                        verbose_name="organización",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="purchases.supplier",
                        verbose_name="proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "departamento de proveedor",
                "verbose_name_plural": "departamentos de proveedor",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierPayment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="monto total pagado",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="fecha de pago"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Efectivo"),
                            ("CHECK", "Cheque"),
                            ("TRANSFER", "Transferencia bancaria"),
                        ],
                        default="TRANSFER",
                        max_length=10,
                        verbose_name="forma de pago",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="referencia"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_payments",
                        to="accounts.organization",
                        verbose_name="organización",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="purchases.supplier",
                        verbose_name="proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "pago a proveedor",
                "verbose_name_plural": "pagos a proveedores",
                "ordering": ["-date", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierPaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="monto aplicado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="purchases.supplierpayment",
                        verbose_name="pago",
                    ),
                ),
                (
                    "supplier_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="purchases.purchasedocument",
                        verbose_name="factura de proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "aplicación de pago",
                "verbose_name_plural": "aplicaciones de pago",
            },
        ),
        migrations.CreateModel(
            name="PurchaseDocumentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="descripción"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="cantidad",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="precio unitario (sin ITBIS)",
                    ),
                ),
                (
                    "itbis_rate",
                    models.CharField(
                        choices=[
                            ("EXEMPT", "Exento (0%)"),
                            ("RATE_0", "Tasa 0% (exportación)"),
                            ("RATE_16", "ITBIS 16%"),
                            ("RATE_18", "ITBIS 18%"),
                        ],
                        default="RATE_18",
                        max_length=8,
                        verbose_name="tasa ITBIS",
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="total línea (sin ITBIS)",
                    ),
                ),
                (
                    "itbis_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="monto ITBIS",
                    ),
                ),
                (
                    "line_total_with_itbis",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="total línea con ITBIS",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_line_items",
                        to="items.item",
                        verbose_name="artículo",
                    ),
                ),
                (
                    "purchase_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchases.purchasedocument",
                        verbose_name="documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "línea de compra",
                "verbose_name_plural": "líneas de compra",
                "ordering": ["pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="purchase_line_quantity_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("unit_price__gte", 0)),
                        name="purchase_line_unit_price_nonneg",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector("name", config="spanish"),
                name="supplier_name_fts_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="supplier_name_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["id_number"],
                name="supplier_id_number_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True),
                    models.Q(("id_number", ""), _negated=True),
                ),
                fields=("organization", "id_number"),
                name="unique_active_supplier_id_per_org",
            ),
        ),
        migrations.AddIndex(
            model_name="purchasedocument",
            index=models.Index(
                fields=["organization", "doc_type", "status"],
                name="pur_org_doctype_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasedocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True),
                    models.Q(("supplier_ncf", ""), _negated=True),
                ),
                fields=("organization", "supplier_ncf"),
                name="unique_supplier_ncf_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierdepartment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("supplier", "name"),
                name="unique_active_supplier_dept_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="supplier_payment_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierpaymentallocation",
            constraint=models.UniqueConstraint(
                fields=("payment", "supplier_invoice"),
                name="unique_supplier_payment_invoice_alloc",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierpaymentallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="supplier_alloc_amount_positive",
            ),
        ),
    ]
