# Generated by Django 5.2.14 on 2026-05-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplierdepartment",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="supplierdepartment",
            name="supplier",
        ),
        migrations.DeleteModel(
            name="HistoricalSupplierDepartment",
        ),
        migrations.DeleteModel(
            name="SupplierDepartment",
        ),
    ]
