# Generated by Django 5.2.14 on 2026-05-29 20:41

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_securityauditevent"),
        ("purchases", "0002_remove_supplierdepartment_organization_and_more"),
        ("sales", "0025_financial_integrity_constraints"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="supplier",
            name="unique_active_supplier_id_per_org",
        ),
        migrations.RemoveIndex(
            model_name="supplier",
            name="supplier_id_number_trgm_idx",
        ),
        migrations.RenameField(
            model_name="historicalsupplier",
            old_name="id_number",
            new_name="rnc_cedula",
        ),
        migrations.RenameField(
            model_name="supplier",
            old_name="id_number",
            new_name="rnc_cedula",
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["rnc_cedula"],
                name="supplier_rnc_cedula_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True),
                    models.Q(("rnc_cedula", ""), _negated=True),
                ),
                fields=("organization", "rnc_cedula"),
                name="unique_active_supplier_rnc_cedula_per_org",
            ),
        ),
    ]
