# Generated by Django 5.2.14 on 2026-05-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "purchases",
            "0003_remove_supplier_unique_active_supplier_id_per_org_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsupplier",
            name="default_ncf_type",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="default_ncf_type",
        ),
    ]
