# Generated by Django 5.2.14 on 2026-06-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_securityauditevent"),
        ("purchases", "0006_simplify_itbis_remove_rate0"),
        ("sales", "0027_simplify_itbis_remove_rate0"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsupplier",
            name="id_type",
            field=models.CharField(
                choices=[("RNC", "RNC"), ("CED", "Cédula")],
                default="RNC",
                max_length=3,
                verbose_name="tipo de identificación",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="id_type",
            field=models.CharField(
                choices=[("RNC", "RNC"), ("CED", "Cédula")],
                default="RNC",
                max_length=3,
                verbose_name="tipo de identificación",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.CheckConstraint(
                condition=models.Q(("id_type__in", ["RNC", "CED"])),
                name="supplier_id_type_rnc_or_cedula",
            ),
        ),
    ]
