# Generated by Django 5.2.13 on 2026-06-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_securityauditevent"),
        ("items", "0012_item_item_org_active_idx"),
        ("purchases", "0007_alter_historicalsupplier_id_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsupplierpayment",
            name="method",
            field=models.CharField(
                choices=[
                    ("CASH", "Efectivo"),
                    ("CHECK", "Cheque"),
                    ("TRANSFER", "Transf. bancaria"),
                ],
                default="TRANSFER",
                max_length=10,
                verbose_name="forma de pago",
            ),
        ),
        migrations.AlterField(
            model_name="supplierpayment",
            name="method",
            field=models.CharField(
                choices=[
                    ("CASH", "Efectivo"),
                    ("CHECK", "Cheque"),
                    ("TRANSFER", "Transf. bancaria"),
                ],
                default="TRANSFER",
                max_length=10,
                verbose_name="forma de pago",
            ),
        ),
        migrations.AddIndex(
            model_name="purchasedocument",
            index=models.Index(
                fields=["organization", "supplier"], name="pur_org_supplier_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasedocument",
            index=models.Index(
                fields=["organization", "doc_type", "status", "issue_date"],
                name="pur_org_dt_status_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="purchasedocumentitem",
            index=models.Index(
                fields=["purchase_document", "itbis_rate"],
                name="pur_item_doc_itbis_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpayment",
            index=models.Index(
                fields=["organization", "supplier", "date"],
                name="suppay_org_supplier_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpayment",
            index=models.Index(
                fields=["organization", "date"], name="suppay_org_date_idx"
            ),
        ),
    ]
