# Generated by Django 6.0.6 on 2026-06-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0010_remove_purchasesequence"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchasedocumentitem",
            options={
                "ordering": ["sort_order", "pk"],
                "verbose_name": "línea de compra",
                "verbose_name_plural": "líneas de compra",
            },
        ),
        migrations.AddField(
            model_name="purchasedocumentitem",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
